Btc wallet exercise, part 1
katiasuya/btcwallet pull request #1
Opened 2020-12-18 06:17 UTC by katiasuya

I didn't do all the test and example functions yet, I'd just like to know if I've understood the task well and if I'm going in the right direction.

2020-12-18 07:46 UTC, papahmsolo requested changes
Good start, but we can do better :)

2020-12-18 07:46 UTC, papahmsolo commented on btcwallet.go
> +
What's a bitcoin part? How about `Bitcoin` as a type name?

2020-12-18 07:46 UTC, papahmsolo commented on btcwallet.go
> +}
We can do this function more compact, you can create and return in one line.
We probably don't need a named return here, it's suggested form the name :)

2020-12-18 07:46 UTC, papahmsolo commented on btcwallet.go
> +}
I think I should've explained it better, we need a method to _get_ the wallet's balance, we can print it to sdtout ourselves if needed.

2020-12-18 07:46 UTC, papahmsolo commented on btcwallet.go
> +}
The structure looks fine, maybe just don't inline the bitcoin type.
I think it's better to ask such questions in the PR, not it code

2020-12-18 07:46 UTC, papahmsolo commented on btcwallet.go
> +}
Shouldn't we have two methods for the wallet: `Deposit` and `Withdraw`?

2020-12-18 08:41 UTC, katiasuya commented on btcwallet.go
> +}
what do you mean by not inlining? doing bitcoin a named field?

2020-12-18 13:37 UTC, papahmsolo commented on btcwallet.go
> +}
Yep

2020-12-18 13:45 UTC, papahmsolo requested changes
See comments

2020-12-18 13:45 UTC, papahmsolo commented on btcwallet.go
>  }
Let's name it `Balance`

2020-12-18 13:45 UTC, papahmsolo commented on btcwallet.go
> +}
- Do we need `else` here? Early return helps here
- Is this `Println` good here?

2020-12-18 13:45 UTC, papahmsolo commented on btcwallet.go
>  }
Again, early return helps. Have a look: https://medium.com/@matryer/line-of-sight-in-code-186dd7cdea88

2020-12-18 13:45 UTC, papahmsolo commented on btcwallet_test.go
> +	w := NewWallet(0)
Even though float and Bitcoin compatible, what does `NewWallet` take as an argument?

2020-12-18 13:56 UTC, katiasuya commented on btcwallet.go
>  }
I was looking at some gophers's repositories and I saw it common to have blnc instead of balance.

2020-12-18 14:45 UTC, katiasuya commented
Have I done it right by just changing balance value instead of creating a new wallet every time in the for loop of Display, Deposit and Withdraw functions?
Should I create test and example functions for NewWallet?

2020-12-21 08:53 UTC, papahmsolo requested changes
Yeah, looks good!
I don't think we need to test the new wallet here.

Also, read up on `t.Run()` and see how can we leverage it for wallet testing.

2020-12-21 08:53 UTC, papahmsolo commented on btcwallet.go
>  }
Why would we want to make it exported or unexported? I think can make the right choice when you'll answer this question.

2020-12-21 08:53 UTC, papahmsolo commented on btcwallet.go
> +	(*w).Balance += b
The pointer will be dereferenced automatically for you, no need for parentheses.

2020-12-21 08:53 UTC, papahmsolo commented on btcwallet.go
> +		return errors.New("Invalid deposit value")
- https://github.com/golang/go/wiki/CodeReviewComments#error-strings
- it's always good to indicate why an error occurs, such as why the deposit value is invalid?

2020-12-21 08:53 UTC, papahmsolo commented on btcwallet_test.go
> +	err := w.Withdraw(1.235)
Does our wallet work with `float` or `Bitcoin` type?

2020-12-21 09:21 UTC, katiasuya commented on btcwallet.go
>  }
I just want it to be accessible for other packages. Or we just don't need it?

2020-12-21 14:08 UTC, papahmsolo commented on btcwallet.go
>  }
What's the problem with having it exported and why do we have `Deposit()` and `Withdraw`?

2020-12-21 14:14 UTC, papahmsolo requested changes
Looks good! Let's make it better 👍 

Can anything go wrong with the `Display()`? I'd use it to assert the balance after we do some manipulations with the wallet. The ExampleDisplay looks good though

2020-12-21 14:14 UTC, papahmsolo commented on btcwallet.go
> +}
Let's call this method `Balance()` as it's returning the wallet's balance.

2020-12-21 14:14 UTC, papahmsolo commented on btcwallet_test.go
> +}
It's a good idea to handle errors like in the previous exmples.

2020-12-21 14:14 UTC, papahmsolo commented on btcwallet_test.go
> +			exp: 105,
Aren't these also `Bitcoins`?

2020-12-22 01:00 UTC, papahmsolo requested changes
Getting better!)

Also, see my previous comments about `t.Run()` and `Bitcoin` type in test data 👍

2020-12-22 08:12 UTC, papahmsolo commented on btcwallet_test.go
> +	}
We can reuse `err` here

2020-12-22 16:25 UTC, papahmsolo commented on btcwallet_test.go
> +}
Maybe we can do something with these errors? LIke, check if we got the right one.

2020-12-22 16:29 UTC, papahmsolo requested changes
This looks great!

Let's improve our tests a little bit, and test different _scenarios_ with deposit and withdrawal.

2020-12-23 08:53 UTC, papahmsolo requested changes
Looks good!

Let's just assert errors and we're ready to go.

2020-12-23 08:53 UTC, papahmsolo commented on btcwallet.go
> +var ErrInsufFunds = errors.New("insufficient funds")
Nice! Let's group them together. Also, you can spell the whole words in the error name just for clarity

2020-12-23 08:53 UTC, papahmsolo commented on btcwallet_test.go
> +			if err == ErrInsufFunds {
Suppose we're making a perfectly legal withdrawal, say we have 10 bitcoins on our balance and want to withdraw 5. And for some reason, our `Withdraw` method returns an error `ErrInsufFunds` this test will pass, but we don't want that, do we?

2020-12-24 10:41 UTC, papahmsolo requested changes
Looks good! Let's make it better :)

2020-12-24 10:41 UTC, papahmsolo commented on btcwallet_test.go
> +		_ = w.Withdraw(tests[0].with)
Almost never a good idea to ignore errors :)

2020-12-24 15:36 UTC, papahmsolo requested changes
This looks excellent! Great job!

2020-12-24 15:36 UTC, papahmsolo commented on btcwallet_test.go
> +	}
Do actually we need this `test` type? We can get by with `Bitcoin` variables inside each `t.Run()`

2020-12-24 15:36 UTC, papahmsolo commented on btcwallet_test.go
> +		}
This feels like repeating yourself, doesn't it? Maybe we can create a helper function to assert the error? We can reuse it in all tests! Also, it's handy to mark such functions with `t.Helper()`

2020-12-24 15:36 UTC, papahmsolo commented on btcwallet_test.go
> +		}
Same here, we're asserting balance many times, worth creating a func.

2020-12-28 08:52 UTC, papahmsolo requested changes
Brilliant! Tests are so clean now.

Some small fixes and we're ready to go.

2020-12-28 08:52 UTC, papahmsolo commented on btcwallet_test.go
> +	}
No need to return here, it'll return anyway

2020-12-28 08:52 UTC, papahmsolo commented on btcwallet_test.go
> +
I don't think we need to assert errors in Examples. They are intended for showing users how to use the wallet.
Something like this should be just fine:
```
	w := NewWallet()
	w.Deposit(Bitcoin(1.235))
	fmt.Println(w.Balance())
```

2020-12-28 11:21 UTC, papahmsolo approved these changes

2020-12-28 11:22 UTC, merged